import "dotenv/config";
import { PrismaClient, Level, Currency, Source } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = `${process.env.DATABASE_URL}`;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);

const prisma = new PrismaClient({ adapter });

const companiesData = [
  {
    name: 'Google',
    slug: 'google',
    normalized_name: 'google',
    industry: 'Technology',
    headquarters: 'Mountain View, CA',
    founded_year: 1998,
    headcount_range: '100,000+',
  },
  {
    name: 'Amazon',
    slug: 'amazon',
    normalized_name: 'amazon',
    industry: 'Ecommerce & Cloud',
    headquarters: 'Seattle, WA',
    founded_year: 1994,
    headcount_range: '100,000+',
  },
  {
    name: 'Microsoft',
    slug: 'microsoft',
    normalized_name: 'microsoft',
    industry: 'Technology',
    headquarters: 'Redmond, WA',
    founded_year: 1975,
    headcount_range: '100,000+',
  },
  {
    name: 'Meta',
    slug: 'meta',
    normalized_name: 'meta',
    industry: 'Social Media',
    headquarters: 'Menlo Park, CA',
    founded_year: 2004,
    headcount_range: '50,000-100,000',
  },
  {
    name: 'NVIDIA',
    slug: 'nvidia',
    normalized_name: 'nvidia',
    industry: 'Semiconductors',
    headquarters: 'Santa Clara, CA',
    founded_year: 1993,
    headcount_range: '20,000-50,000',
  },
  {
    name: 'Flipkart',
    slug: 'flipkart',
    normalized_name: 'flipkart',
    industry: 'Ecommerce',
    headquarters: 'Bengaluru, India',
    founded_year: 2007,
    headcount_range: '10,000-50,000',
  },
  {
    name: 'Meesho',
    slug: 'meesho',
    normalized_name: 'meesho',
    industry: 'Social Commerce',
    headquarters: 'Bengaluru, India',
    founded_year: 2015,
    headcount_range: '1,000-5,000',
  },
  {
    name: 'Razorpay',
    slug: 'razorpay',
    normalized_name: 'razorpay',
    industry: 'Fintech',
    headquarters: 'Bengaluru, India',
    founded_year: 2014,
    headcount_range: '1,000-5,000',
  },
  {
    name: 'Zepto',
    slug: 'zepto',
    normalized_name: 'zepto',
    industry: 'Quick Commerce',
    headquarters: 'Mumbai, India',
    founded_year: 2021,
    headcount_range: '1,000-5,000',
  },
  {
    name: 'Infosys',
    slug: 'infosys',
    normalized_name: 'infosys',
    industry: 'IT Services',
    headquarters: 'Bengaluru, India',
    founded_year: 1981,
    headcount_range: '100,000+',
  },
  {
    name: 'TCS',
    slug: 'tcs',
    normalized_name: 'tcs',
    industry: 'IT Services',
    headquarters: 'Mumbai, India',
    founded_year: 1968,
    headcount_range: '100,000+',
  },
  {
    name: 'Wipro',
    slug: 'wipro',
    normalized_name: 'wipro',
    industry: 'IT Services',
    headquarters: 'Bengaluru, India',
    founded_year: 1945,
    headcount_range: '100,000+',
  },
];

// Seed mapping of salaries
const salariesData: Array<{
  companySlug: string;
  role: string;
  level: Level;
  location: string;
  currency: Currency;
  experience_years: number;
  base_salary: number;
  bonus: number;
  stock: number;
  source: Source;
  confidence_score: number;
  is_verified: boolean;
  submitted_days_ago?: number;
}> = [
  // --- ZEРTO (Single-record company edge case) ---
  {
    companySlug: 'zepto',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1800000,
    bonus: 200000,
    stock: 400000,
    source: Source.OFFER_LETTER,
    confidence_score: 1.0,
    is_verified: true,
  },

  // --- GOOGLE ---
  // Edge Case: Principal SDE / High Compensation / USD
  {
    companySlug: 'google',
    role: 'Principal Engineer',
    level: Level.PRINCIPAL,
    location: 'Mountain View',
    currency: Currency.USD,
    experience_years: 15,
    base_salary: 350000,
    bonus: 150000,
    stock: 500000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  // Google India SDE-I (No stock / No bonus edge case)
  {
    companySlug: 'google',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 0,
    base_salary: 1600000,
    bonus: 0,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.6,
    is_verified: false,
  },
  // Google standard distributions
  {
    companySlug: 'google',
    role: 'Software Engineer II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 2800000,
    bonus: 300000,
    stock: 800000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 7,
    base_salary: 4500000,
    bonus: 500000,
    stock: 1500000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Staff Software Engineer',
    level: Level.STAFF,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 11,
    base_salary: 6500000,
    bonus: 800000,
    stock: 3000000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Mountain View',
    currency: Currency.USD,
    experience_years: 1,
    base_salary: 140000,
    bonus: 15000,
    stock: 45000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.98,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Software Engineer III',
    level: Level.SDE_III,
    location: 'Mountain View',
    currency: Currency.USD,
    experience_years: 8,
    base_salary: 210000,
    bonus: 40000,
    stock: 120000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },

  // --- AMAZON ---
  // Amazon USD High Compensation SDE III
  {
    companySlug: 'amazon',
    role: 'SDE III',
    level: Level.SDE_III,
    location: 'Seattle',
    currency: Currency.USD,
    experience_years: 9,
    base_salary: 220000,
    bonus: 60000,
    stock: 140000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.92,
    is_verified: true,
  },
  // Amazon India SDE-I with Zero Stock
  {
    companySlug: 'amazon',
    role: 'SDE I',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1500000,
    bonus: 300000,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.7,
    is_verified: false,
  },
  {
    companySlug: 'amazon',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 2600000,
    bonus: 400000,
    stock: 600000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'amazon',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 5,
    base_salary: 3100000,
    bonus: 500000,
    stock: 800000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'amazon',
    role: 'SDE III',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 8,
    base_salary: 4800000,
    bonus: 600000,
    stock: 1800000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'amazon',
    role: 'Principal SDE',
    level: Level.PRINCIPAL,
    location: 'Seattle',
    currency: Currency.USD,
    experience_years: 16,
    base_salary: 310000,
    bonus: 0, // Zero bonus Principal
    stock: 450000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },

  // --- MICROSOFT ---
  {
    companySlug: 'microsoft',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 2,
    base_salary: 1650000,
    bonus: 150000,
    stock: 300000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Software Engineer II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 5,
    base_salary: 2700000,
    bonus: 300000,
    stock: 650000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'Redmond',
    currency: Currency.USD,
    experience_years: 8,
    base_salary: 195000,
    bonus: 35000,
    stock: 80000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Principal SDE',
    level: Level.PRINCIPAL,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 14,
    base_salary: 7500000,
    bonus: 1200000,
    stock: 3500000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Staff SDE',
    level: Level.STAFF,
    location: 'Redmond',
    currency: Currency.USD,
    experience_years: 12,
    base_salary: 250000,
    bonus: 50000,
    stock: 180000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.94,
    is_verified: true,
  },

  // --- META ---
  // High Equity Meta SDE-II (INR and USD cases)
  {
    companySlug: 'meta',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'London',
    currency: Currency.USD, // Standardize to USD for global
    experience_years: 1,
    base_salary: 125000,
    bonus: 12000,
    stock: 60000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.96,
    is_verified: true,
  },
  {
    companySlug: 'meta',
    role: 'Production Engineer II',
    level: Level.SDE_II,
    location: 'Menlo Park',
    currency: Currency.USD,
    experience_years: 4,
    base_salary: 185000,
    bonus: 25000,
    stock: 130000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.98,
    is_verified: true,
  },
  {
    companySlug: 'meta',
    role: 'Software Engineer',
    level: Level.SDE_III,
    location: 'Menlo Park',
    currency: Currency.USD,
    experience_years: 8,
    base_salary: 240000,
    bonus: 45000,
    stock: 220000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'meta',
    role: 'Software Engineer',
    level: Level.STAFF,
    location: 'Menlo Park',
    currency: Currency.USD,
    experience_years: 11,
    base_salary: 310000,
    bonus: 60000,
    stock: 400000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.97,
    is_verified: true,
  },

  // --- NVIDIA ---
  {
    companySlug: 'nvidia',
    role: 'Hardware Engineer II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 2200000,
    bonus: 250000,
    stock: 500000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'nvidia',
    role: 'Senior Systems Architect',
    level: Level.SDE_III,
    location: 'Pune',
    currency: Currency.INR,
    experience_years: 8,
    base_salary: 3800000,
    bonus: 400000,
    stock: 1200000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'nvidia',
    role: 'Principal Engineer',
    level: Level.PRINCIPAL,
    location: 'Santa Clara',
    currency: Currency.USD,
    experience_years: 15,
    base_salary: 290000,
    bonus: 50000,
    stock: 350000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.96,
    is_verified: true,
  },

  // --- FLIPKART ---
  {
    companySlug: 'flipkart',
    role: 'SDE I',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1600000,
    bonus: 150000,
    stock: 200000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'flipkart',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 2700000,
    bonus: 250000,
    stock: 550000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    companySlug: 'flipkart',
    role: 'SDE III',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 7,
    base_salary: 4200000,
    bonus: 400000,
    stock: 1200000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },

  // --- MEESHO ---
  {
    companySlug: 'meesho',
    role: 'SDE I',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1400000,
    bonus: 0,
    stock: 200000,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.8,
    is_verified: false,
  },
  {
    companySlug: 'meesho',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 2500000,
    bonus: 200000,
    stock: 400000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.93,
    is_verified: true,
  },
  {
    companySlug: 'meesho',
    role: 'SDE III',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 7,
    base_salary: 3900000,
    bonus: 300000,
    stock: 800000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.92,
    is_verified: true,
  },

  // --- RAZORPAY ---
  {
    companySlug: 'razorpay',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1300000,
    bonus: 100000,
    stock: 150000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    companySlug: 'razorpay',
    role: 'Senior Software Engineer',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 2400000,
    bonus: 200000,
    stock: 400000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'razorpay',
    role: 'Staff Software Engineer',
    level: Level.STAFF,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 9,
    base_salary: 4800000,
    bonus: 400000,
    stock: 1000000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },

  // --- INFOSYS (IT Services Mass Recruiters) ---
  // Edge Case: Zero Bonus / Zero Stock / Low Comp SDE I
  {
    companySlug: 'infosys',
    role: 'Systems Engineer',
    level: Level.SDE_I,
    location: 'Mysore',
    currency: Currency.INR,
    experience_years: 0,
    base_salary: 360000,
    bonus: 0,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.85,
    is_verified: true,
  },
  {
    companySlug: 'infosys',
    role: 'Senior Systems Engineer',
    level: Level.SDE_II,
    location: 'Pune',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 650000,
    bonus: 50000,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.75,
    is_verified: false,
  },
  {
    companySlug: 'infosys',
    role: 'Technology Analyst',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 6,
    base_salary: 1100000,
    bonus: 100000,
    stock: 0,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'infosys',
    role: 'Technology Architect',
    level: Level.STAFF,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 12,
    base_salary: 2200000,
    bonus: 200000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },

  // --- TCS ---
  {
    companySlug: 'tcs',
    role: 'Assistant System Engineer',
    level: Level.SDE_I,
    location: 'Chennai',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 340000,
    bonus: 20000,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.8,
    is_verified: false,
  },
  {
    companySlug: 'tcs',
    role: 'System Engineer',
    level: Level.SDE_II,
    location: 'Mumbai',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 600000,
    bonus: 40000,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.7,
    is_verified: false,
  },
  {
    companySlug: 'tcs',
    role: 'IT Analyst',
    level: Level.SDE_III,
    location: 'Delhi',
    currency: Currency.INR,
    experience_years: 7,
    base_salary: 1050000,
    bonus: 80000,
    stock: 0,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'tcs',
    role: 'Consultant',
    level: Level.STAFF,
    location: 'Mumbai',
    currency: Currency.INR,
    experience_years: 13,
    base_salary: 2600000,
    bonus: 300000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.93,
    is_verified: true,
  },

  // --- WIPRO ---
  {
    companySlug: 'wipro',
    role: 'Project Engineer',
    level: Level.SDE_I,
    location: 'Kochi',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 350000,
    bonus: 0,
    stock: 0,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.7,
    is_verified: false,
  },
  {
    companySlug: 'wipro',
    role: 'Senior Project Engineer',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 720000,
    bonus: 60000,
    stock: 0,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'wipro',
    role: 'Team Leader',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 8,
    base_salary: 1300000,
    bonus: 120000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.92,
    is_verified: true,
  },

  // --- Extra padding entries to hit > 65 records ---
  // (Adding additional distribution variants across target companies)
  {
    companySlug: 'google',
    role: 'Software Engineer II',
    level: Level.SDE_II,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 3000000,
    bonus: 400000,
    stock: 750000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 6,
    base_salary: 4200000,
    bonus: 450000,
    stock: 1200000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    companySlug: 'google',
    role: 'Staff Engineer',
    level: Level.STAFF,
    location: 'Mountain View',
    currency: Currency.USD,
    experience_years: 10,
    base_salary: 270000,
    bonus: 55000,
    stock: 220000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.98,
    is_verified: true,
  },
  {
    companySlug: 'amazon',
    role: 'SDE II',
    location: 'Hyderabad',
    level: Level.SDE_II,
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 2400000,
    bonus: 300000,
    stock: 500000,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.8,
    is_verified: false,
  },
  {
    companySlug: 'amazon',
    role: 'SDE I',
    level: Level.SDE_I,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1600000,
    bonus: 250000,
    stock: 300000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'amazon',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 9,
    base_salary: 4900000,
    bonus: 500000,
    stock: 1600000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Software Engineer',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1500000,
    bonus: 100000,
    stock: 250000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 9,
    base_salary: 4000000,
    bonus: 450000,
    stock: 1100000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'microsoft',
    role: 'Software Engineer II',
    level: Level.SDE_II,
    location: 'Hyderabad',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 2500000,
    bonus: 250000,
    stock: 500000,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.88,
    is_verified: false,
  },
  {
    companySlug: 'meta',
    role: 'Software Engineer II',
    level: Level.SDE_II,
    location: 'London',
    currency: Currency.USD,
    experience_years: 3,
    base_salary: 155000,
    bonus: 20000,
    stock: 90000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.95,
    is_verified: true,
  },
  {
    companySlug: 'meta',
    role: 'Senior Software Engineer',
    level: Level.SDE_III,
    location: 'London',
    currency: Currency.USD,
    experience_years: 7,
    base_salary: 215000,
    bonus: 35000,
    stock: 170000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.96,
    is_verified: true,
  },
  {
    companySlug: 'nvidia',
    role: 'Hardware Engineer I',
    level: Level.SDE_I,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 1,
    base_salary: 1500000,
    bonus: 150000,
    stock: 300000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.92,
    is_verified: true,
  },
  {
    companySlug: 'nvidia',
    role: 'Senior Systems Software Engineer',
    level: Level.SDE_III,
    location: 'Santa Clara',
    currency: Currency.USD,
    experience_years: 9,
    base_salary: 210000,
    bonus: 35000,
    stock: 110000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    companySlug: 'flipkart',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 3,
    base_salary: 2500000,
    bonus: 200000,
    stock: 450000,
    source: Source.ANONYMOUS_USER,
    confidence_score: 0.85,
    is_verified: false,
  },
  {
    companySlug: 'meesho',
    role: 'SDE II',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 4,
    base_salary: 2800000,
    bonus: 250000,
    stock: 450000,
    source: Source.OFFER_LETTER,
    confidence_score: 0.9,
    is_verified: true,
  },
  {
    companySlug: 'razorpay',
    role: 'Senior Software Engineer',
    level: Level.SDE_II,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 5,
    base_salary: 2650000,
    bonus: 250000,
    stock: 450000,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.94,
    is_verified: true,
  },
  {
    companySlug: 'infosys',
    role: 'Senior Consultant',
    level: Level.STAFF,
    location: 'Pune',
    currency: Currency.INR,
    experience_years: 14,
    base_salary: 2400000,
    bonus: 250000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.91,
    is_verified: true,
  },
  {
    companySlug: 'tcs',
    role: 'Lead Consultant',
    level: Level.PRINCIPAL,
    location: 'Mumbai',
    currency: Currency.INR,
    experience_years: 18,
    base_salary: 4200000,
    bonus: 500000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.96,
    is_verified: true,
  },
  {
    companySlug: 'wipro',
    role: 'Architect',
    level: Level.STAFF,
    location: 'Bengaluru',
    currency: Currency.INR,
    experience_years: 12,
    base_salary: 2100000,
    bonus: 180000,
    stock: 0,
    source: Source.VERIFIED_EMAIL,
    confidence_score: 0.9,
    is_verified: true,
  },
];

async function main() {
  console.log('Clearing database tables...');
  await prisma.salary.deleteMany({});
  await prisma.company.deleteMany({});

  console.log('Seeding Companies...');
  const createdCompanies = await Promise.all(
    companiesData.map(async (company) => {
      return prisma.company.create({
        data: company,
      });
    })
  );

  console.log(`Created ${createdCompanies.length} companies.`);

  // Create lookup map to map slugs to created company IDs
  const companySlugToIdMapMap: Record<string, string> = {};
  createdCompanies.forEach((company) => {
    companySlugToIdMapMap[company.slug] = company.id;
  });

  console.log('Seeding Salaries...');
  let seedCount = 0;
  for (const sal of salariesData) {
    const companyId = companySlugToIdMapMap[sal.companySlug];
    if (!companyId) {
      console.warn(`Warning: Company ID not found for slug "${sal.companySlug}". Skipping...`);
      continue;
    }

    const totalCompensation = sal.base_salary + sal.bonus + sal.stock;

    await prisma.salary.create({
      data: {
        company_id: companyId,
        role: sal.role,
        level: sal.level,
        location: sal.location,
        currency: sal.currency,
        experience_years: sal.experience_years,
        base_salary: sal.base_salary,
        bonus: sal.bonus,
        stock: sal.stock,
        total_compensation: totalCompensation,
        source: sal.source,
        confidence_score: sal.confidence_score,
        is_verified: sal.is_verified,
        submitted_at: sal.submitted_days_ago
          ? new Date(Date.now() - sal.submitted_days_ago * 24 * 60 * 60 * 1000)
          : new Date(),
      },
    });
    seedCount++;
  }

  console.log(`Seeding complete! Successfully created ${seedCount} salary records.`);
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
